config/routes.rb
Rails.application.routes.draw do
  
  root 'pictures#index'

  resources :pictures
  
  resources :users, only: [:new, :create, :show, :update, :edit]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get  '*path', controller: 'application', action: 'render_404'
  post '*path', controller: 'application', action: 'render_404'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  # validates :title, presence: true
  default_scope -> { order(created_at: :desc) }
  validates :comment, length: { in: 0..140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates_uniqueness_of :email, :message => "already exists."
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  # ↑ on: create を入れることで、作成時のみpasswordのチェックをする。
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500
  
  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
  
  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(picture_id: params[:picture_id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :set_login, only: [:new, :edit, :show, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id


    respond_to do |format|
      if @picture.save
        format.html { redirect_and_mail(@picture, "作成")  }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_and_mail(@picture, "編集") }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_and_mail( @picture, "削除") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end
    
    def redirect_and_mail(picture, action)
      @picture = picture
      @action = action
      PictureMailer.picture_mail(@picture, @action).deliver
      redirect_to pictures_path, notice: "ピクチャを" + @action + "しました！"
    end
  
    def set_login
      if !logged_in?
        redirect_to new_session_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to new_session_path
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :set_login, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
  end
  
  def update
    puts "hello!!"
    puts avatar_params
    @user.update(avatar_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :avatar)
  end
  
  def avatar_params
    params.require(:user).permit(:avatar, :remove_avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def set_login
    if !logged_in?
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clonistagram</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>
  <% if current_page?(:controller => 'sessions', :action => 'new') %>
  <body class="login_bg">
  <% else %>
  <body>
    <div style="width:100%" class="bg-primary">
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary navbar-ym">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Clonistagram</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to '', new_picture_path, class: "fa fa-camera fa-lg fa-ym-white nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to '', pictures_path, class: "fa fa-book fa-lg fa-ym-white nav-link" %>
          </li>
        </ul>
          <% if logged_in? %>
            <li class="nav-item active">
              <%= link_to current_user.name, user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "nav-link"%>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Sign up", new_user_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
            <%= link_to "Login", new_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    </div>
  <% end %>
    <div class="container">
    <%= yield %>
    </div>
    <% unless current_page?(:controller => 'sessions', :action => 'new') %>
  　<footer class="footer bg-primary">
        <p>Copyright © 2018 Tomoyuki YAMAZAKI/2017-09 ALL RIGHTS RESERVED</p>
    </footer>
    <% end %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  
  <span class="row">
    <% unless @picture.image.file.nil? %>
    <%= image_tag @picture.image_url %>
    <% end %>
  </span>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :picture_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.1.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Comment</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td>
          <% unless picture.image.file.nil? %>
          <%= image_tag picture.image_url %>
          <% end %>
        </td>
        <td><%= picture.comment %></td>
        <td>
          <%= link_to 'Show', picture %>
          <% if picture.user == current_user %>
            <%= link_to 'Edit', edit_picture_path(picture) %>
            <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title">Card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<div class="col-md-12" >
  <div class="card-columns"> 
  <% @pictures.each do |picture| %>
    <div class="card" >
    <!-- <div class="card" style="width: 20rem;"> -->
      <% unless picture.image.file.nil? %>
        <%= image_tag picture.image_url, class: "card-img-top img-fluid" %>
      <% end %>
      <div class="card-block">
        <!-- <h4 class="card-title">Card title</h4> -->
        <h6 class="card-subtitle mb-2 text-muted" style="display: inline-block">
          <%= picture.user.name %> 
        </h6>
        <h6 class="card-subtitle mb-2 text-muted" style="display: inline-block;padding:0 10px;">
          <%= picture.created_at %>
        </h6>
        <p class="card-text">
          <%= picture.comment %>
        </p>
        <%= link_to 'Show', picture, class: "btn btn-primary" %>
        <% if picture.user == current_user %>
          <%= link_to 'Edit', edit_picture_path(picture) , class: "btn btn-primary"%>
          <%= link_to 'Destroy', picture, method: :delete, 
              data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  <% end %>
  </div> 
</div>

<br>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>投稿者: <%= @picture.user.name %></p>

<p>
  <% unless @picture.image.file.nil? %>
  <%= image_tag @picture.image_url %>
  <% end %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @picture.comment %>
</p>

<% unless @picture.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(picture_id: @picture.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <%= link_to 'Edit', edit_picture_path(@picture) %> |
<% end %>
<%= link_to 'Back', pictures_path %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: user_path, html: { multipart: true, :id=>'form_id' } ) do |form| %>

  <div class="row">
    <div class="col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-9 col-xs-offset-3">
      <%= form.file_field :avatar, id: :user_avatar %>
    </div>
      <%= 
        #form.hidden_field :image_cache
        form.hidden_field :avatar_cache
      %>
  </div>
  <div class="actions centerize">
    <%= form.submit 'アバターを更新', class: "btn btn-default" %>
    <%=
      link_to 'アバターを削除', user_path(@user, user: {remove_avatar: 1} ), method: :put,
          data: { confirm: 'アバターを削除しますか?' }, class: 'btn btn-danger'
    %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='row'>
  <div class='profile col-md-6'>
    <div class='inner-edit'>
      <h1 class="centerize">Profile</h1>
      <h4 class="widthall">Name: <%= @user.name %></h4>
      <h4 class="widthall">Email: <%= @user.email %></h4>
      
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='row'>
  <div class='profile col-md-6'>
    <div class='inner-edit'>
      <h1 class="centerize">Sign up</h1>
      <% if @user.errors.any? %>
        <div id="error_explanation centerize">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="row">
          <%= f.label :name %>
          <%= f.text_field :name, class: "widthall" %>
        </div>
        <div class="row">
          <%= f.label :email %>
          <%= f.email_field :email, class: "widthall" %>
        </div>
        <div class="row">
          <%= f.label :password  %>
          <%= f.password_field :password, class: "widthall" %>
        </div>
        <div class="row">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "widthall" %>
        </div>
        <div class="row">
          <%= f.label :avatar, class: "col-md-3" %>
          <div class="col-md-9">※アバターはあとで編集できます。</div>
          <%= 
            f.file_field :avatar, id: :user_avatar, class: "col-md-8"
          %>
          <%= f.hidden_field :avatar_cache %>
        </div>
        <div class="row">
        <%= f.submit "Create my account", class: "btn-ym btn-ym-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-4 side_menu">
  <div style="float: left;padding-right: 5px;">
    <p><%= image_tag @user.avatar_url %></p>
  </div>
  <h4><%= @user.name %></h4>
  <p><%= @user.email %></p>
  <p>
    <%= 
    link_to 'アバター編集', edit_user_path(@user)
    %> 
  </p>
</div>
<p id="notice"><%= notice %></p>
<h1>Favarites</h1>
<div class="col-md-8">
  <div class="card-columns"> 
  <% @user.favorite_pictures.each do |picture| %>
    <div class="card">
      <p>
        <% unless picture.image.file.nil? %>
        <%= image_tag picture.image_url, class: "card-img-top img-fluid" %>
        <% end %>
      </p>
      <div class="card-block">
        <p class="card-text"><%= picture.comment %></p>
        <h6 class="card-subtitle mb-2 text-muted" style="display: inline-block">
          <%= picture.user.name %> 
        </h6>
        <h6 class="card-subtitle mb-2 text-muted" style="display: inline-block;padding:0 10px;">
          <%= picture.created_at %>
        </h6>
        <%= link_to 'Show', picture, class: 'btn btn-primary' %>
        <% if picture.user == current_user %>
          <%= link_to 'Edit', edit_picture_path(picture), class: 'btn btn-info' %> |
          <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

<br>